name: Build-api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run build for api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18'

      - name: Run build
        run: go build
