name: Build-web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run build for web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run build
        run: npm run build

  run-linters:
    name: Run linters for web
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint