name: Build-api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run build for api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18'

      - name: Run build
        run: go build

  tests:
    name: Run tests for api
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18'

      - name: Run build
        run: go test ./...
